In [7]:
import run_model
import pandas as pd

In [12]:
Study_iter = 5 # number of study iterations to complete
ID = "Run1" # ID for outputfile
folder = "ExampleFolder" # Folder to which results are output
rootfolder = "C:/Users/atully/Jupyter/Notebooks/PI Models/" # path to folder holding code files
# to sample blocking behavior set a and/or b to "SAMPLE" - (a = "SAMPLE")
a = 1.05
b = 1.5
lam = 0.3
Blab = 8
Banc = 8
# Experiment key can be set to: "Coe", "IZZI", "Aitken", "Thellier"
Experiment_Key = "IZZI"

In [13]:
# run model
run_model.run(Study_iter,ID, folder, rootfolder, a, b, lam, Blab, Banc, Experiment_Key)

ExampleFolder/Run1_Out.csv has been deleted
Programme Initiated: Wed, 31 Jul 2024 06:32:37
C:/Users/atully/Jupyter/Notebooks/PI Models//Core_Files/Experiment_IZZI.txt
Study Iteration: 0
time: 31.875832319259644
Study 0 complete
Study Iteration: 1
time: 33.4643976688385
Study 1 complete
Study Iteration: 2
time: 31.33075737953186
Study 2 complete
Study Iteration: 3
time: 34.57471299171448
Study 3 complete
Study Iteration: 4
time: 34.044910192489624
Study 4 complete
--- 171.36371660232544 seconds ---


---Average time per sample: 33.058122110366824 seconds ---


--- Run Time:  00:00:02:51  ---
END
Programme Finished: Wed, 31 Jul 2024 06:35:28

In [14]:
file = f"{rootfolder}{folder}/{ID}_Out.csv"
df = pd.read_csv(file)

In [15]:
display(df.describe())

,nmax,Blab,Anis_c,n,Tmin,Tmax,xbar,ybar,b,Banc,...,NLT_a_est,NLT_b_est,dTRM_NLT,dTRM_Anis,Lambda,blocking a,blocking b,Bexp,Accuracy,Simulation
count,455.0,455.0,0.0,455.000000,455.000000,455.000000,455.000000,455.000000,455.000000,455.000000,...,0.0,0.0,0.0,0.0,4.550000e+02,4.550000e+02,455.0,455.0,455.000000,455.00000
mean,14.0,8.0,NaN,6.000000,47.271694,87.087912,3.169082,0.955301,-0.764932,7.248571,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,0.906071,2.00000
std,0.0,0.0,NaN,3.165758,33.510441,19.735476,1.109301,0.961357,1.626442,12.417342,...,NaN,NaN,NaN,NaN,1.167017e-15,7.780115e-15,0.0,0.0,1.552168,1.41577
min,14.0,8.0,NaN,2.000000,0.000000,12.931034,0.139778,0.008257,-14.870000,0.100000,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,0.012500,0.00000
25%,14.0,8.0,NaN,3.000000,12.931034,86.206897,2.496797,0.166885,-0.934000,4.100000,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,0.512500,1.00000
50%,14.0,8.0,NaN,5.000000,38.793103,97.413793,3.371775,0.647230,-0.701000,5.700000,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,0.712500,2.00000
75%,14.0,8.0,NaN,8.000000,77.586207,99.137931,4.155494,1.420717,-0.504500,7.500000,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,0.937500,3.00000
max,14.0,8.0,NaN,14.000000,99.137931,100.000000,4.512429,4.221728,25.517000,204.100000,...,NaN,NaN,NaN,NaN,3.000000e-01,1.050000e+00,1.5,8.0,25.512500,4.00000

In [16]:
display(df.head())

,Meas_Data,Meas_Treatment,Meas_Temp,Blab_orient,Xpts,Ypts,x_prime_scaled,y_prime_scaled,nmax,Temp_steps,...,dTRM_Anis,NRM_in_TRM,Lambda,Lam. Dist.,blocking a,blocking b,N_orient,Bexp,Accuracy,Simulation
0,[[-3.20980009e+00 -7.93161849e-01 -3.05534215e...,[1. 0. 1. 3. 1. 0. 2. 0. 1. 3. 1. 0. 2. 0. 1. ...,[[100. ]\n [ 12.93103448]\n [ 12.931034...,[[0 0 1]],[[0. ]\n [1.00453799]\n [0.63590645]\n ...,[[4.50189271e+00]\n [3.90773392e+00]\n [2.2122...,[[0.]\n [1.]],[[1. ]\n [0.86802022]],14,[ 0. 12.93103448 25.86206897 38.79...,...,NaN,[ True True True True True True True Tr...,0.3,nan nan,1.05,1.5,[[-0.73787542 -0.11674179 -0.66476403]],8,0.5875,0
1,[[-3.20980009e+00 -7.93161849e-01 -3.05534215e...,[1. 0. 1. 3. 1. 0. 2. 0. 1. 3. 1. 0. 2. 0. 1. ...,[[100. ]\n [ 12.93103448]\n [ 12.931034...,[[0 0 1]],[[0. ]\n [1.00453799]\n [0.63590645]\n ...,[[4.50189271e+00]\n [3.90773392e+00]\n [2.2122...,[[0.10668798]\n [1.096345 ]\n [1.37666162]],[[1.03523516]\n [0.70838741]\n [0.61580902]],14,[ 0. 12.93103448 25.86206897 38.79...,...,NaN,[ True True True True True True True Tr...,0.3,nan nan,1.05,1.5,[[-0.73787542 -0.11674179 -0.66476403]],8,2.3375,0
2,[[-3.20980009e+00 -7.93161849e-01 -3.05534215e...,[1. 0. 1. 3. 1. 0. 2. 0. 1. 3. 1. 0. 2. 0. 1. ...,[[100. ]\n [ 12.93103448]\n [ 12.931034...,[[0 0 1]],[[0. ]\n [1.00453799]\n [0.63590645]\n ...,[[4.50189271e+00]\n [3.90773392e+00]\n [2.2122...,[[0.01888134]\n [0.40559259]\n [0.57428654]\n ...,[[1.01291893]\n [0.74832452]\n [0.63290125]\n ...,14,[ 0. 12.93103448 25.86206897 38.79...,...,NaN,[ True True True True True True True Tr...,0.3,nan nan,1.05,1.5,[[-0.73787542 -0.11674179 -0.66476403]],8,1.7750,0
3,[[-3.20980009e+00 -7.93161849e-01 -3.05534215e...,[1. 0. 1. 3. 1. 0. 2. 0. 1. 3. 1. 0. 2. 0. 1. ...,[[100. ]\n [ 12.93103448]\n [ 12.931034...,[[0 0 1]],[[0. ]\n [1.00453799]\n [0.63590645]\n ...,[[4.50189271e+00]\n [3.90773392e+00]\n [2.2122...,[[0.03119939]\n [0.38936833]\n [0.52090868]\n ...,[[1.02521334]\n [0.73576427]\n [0.62946182]\n ...,14,[ 0. 12.93103448 25.86206897 38.79...,...,NaN,[ True True True True True True True Tr...,0.3,nan nan,1.05,1.5,[[-0.73787542 -0.11674179 -0.66476403]],8,2.0000,0
4,[[-3.20980009e+00 -7.93161849e-01 -3.05534215e...,[1. 0. 1. 3. 1. 0. 2. 0. 1. 3. 1. 0. 2. 0. 1. ...,[[100. ]\n [ 12.93103448]\n [ 12.931034...,[[0 0 1]],[[0. ]\n [1.00453799]\n [0.63590645]\n ...,[[4.50189271e+00]\n [3.90773392e+00]\n [2.2122...,[[-0.01681719]\n [ 0.20825625]\n [ 0.33306895]...,[[0.98276819]\n [0.75214577]\n [0.62425593]\n ...,14,[ 0. 12.93103448 25.86206897 38.79...,...,NaN,[ True True True True True True True Tr...,0.3,nan nan,1.05,1.5,[[-0.73787542 -0.11674179 -0.66476403]],8,1.4750,0